"""empty message

Revision ID: 5b7c81805c60
Revises: 
Create Date: 2022-04-24 22:23:40.813638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7c81805c60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('surname', sa.String(length=16), nullable=True),
    sa.Column('face', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_area_area_name', table_name='area')
    op.drop_table('area')
    op.drop_column('post', 'area_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('area_id', sa.INTEGER(), nullable=True))
    op.create_table('area',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('coords', sa.VARCHAR(length=64), nullable=True),
    sa.Column('href', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_area_area_name', 'area', ['area_name'], unique=False)
    op.drop_table('person')
    # ### end Alembic commands ###
